In [ ]:
import pandas as pd

In [4]:
df = pd.read_json("data/radar_data.json")

In [5]:
df

,generated_at,count,items
0,2026-04-08 05:01:10+00:00,2035,"{'cve_id': 'CVE-2026-0005', 'description': 'In..."
1,2026-04-08 05:01:10+00:00,2035,"{'cve_id': 'CVE-2026-0006', 'description': 'In..."
2,2026-04-08 05:01:10+00:00,2035,"{'cve_id': 'CVE-2026-0007', 'description': 'In..."
3,2026-04-08 05:01:10+00:00,2035,"{'cve_id': 'CVE-2026-0008', 'description': 'In..."
4,2026-04-08 05:01:10+00:00,2035,"{'cve_id': 'CVE-2026-0010', 'description': 'In..."
...,...,...,...
2030,2026-04-08 05:01:10+00:00,2035,"{'cve_id': 'CVE-2026-5733', 'description': 'In..."
2031,2026-04-08 05:01:10+00:00,2035,"{'cve_id': 'CVE-2026-5734', 'description': 'Me..."
2032,2026-04-08 05:01:10+00:00,2035,"{'cve_id': 'CVE-2026-5735', 'description': 'Me..."
2033,2026-04-08 05:01:10+00:00,2035,"{'cve_id': 'CVE-2026-5741', 'description': 'A ..."
2034,2026-04-08 05:01:10+00:00,2035,"{'cve_id': 'CVE-2026-5745', 'description': 'A ..."

In [6]:
df.head()

,generated_at,count,items
0,2026-04-08 05:01:10+00:00,2035,"{'cve_id': 'CVE-2026-0005', 'description': 'In..."
1,2026-04-08 05:01:10+00:00,2035,"{'cve_id': 'CVE-2026-0006', 'description': 'In..."
2,2026-04-08 05:01:10+00:00,2035,"{'cve_id': 'CVE-2026-0007', 'description': 'In..."
3,2026-04-08 05:01:10+00:00,2035,"{'cve_id': 'CVE-2026-0008', 'description': 'In..."
4,2026-04-08 05:01:10+00:00,2035,"{'cve_id': 'CVE-2026-0010', 'description': 'In..."